### ISSUE TITLE
Move platform icon into metadata on user page & wherever else this is happening

### ISSUE THREAD

**Issue by ethteck** [decompme/decomp.me#1111]
<img width="568" alt="image" src="https://github.com/decompme/decomp.me/assets/2985314/da660576-f86a-493e-87e0-b6a4569d4201">

**Comment by ethteck** [comment]
1111

**Comment by bates64** [comment]
I don't see the issue. Can you explain more / point it out in the screenshot?

**Comment by bates64** [comment]
If you're talking about the icon being on a separate line to the game name, that seems intentional according to the code. It isn't a line break; the icon is in `.header` and the game name is in `.metadata`.

**Comment by ethteck** [comment]
I just mean visually they're on two lines, and it's not intended for this component

**Comment by bates64** [comment]
<img width="906" alt="image" src="https://github.com/decompme/decomp.me/assets/9429556/49e84d92-7435-4c1f-a247-7091e7d41071">

I disagree that this is a bug. It was an intentional change in #1102.

**Comment by bates64** [comment]
The real issue here IMO is the scratch name being aligned to the right due to the lack of username.

**Comment by bates64** [comment]
There is other content in the header "line": the scratch name. It's just aligned to the right
