### ISSUE TITLE
[BUG] User scratch list has unexpected link sizes

### ISSUE THREAD

**Issue by marijnvdwerf** [decompme/decomp.me#1129]
The cards/tiles on a user page that show recent scratches have unexpected touch target sizes. The platform icon (yellow) is unexpectedly large. Possibly as a result from this element being reused from the front page (minus the username?)

UX-wise, I'd expect the whole tile to be a link to the scratch, as opposed to it linking out to 3 different destinations.

<img width="781" alt="image" src="https://github.com/decompme/decomp.me/assets/737603/19ad7aa1-d759-48e3-a403-a95be73f704a">

**Comment by wearrrrr** [comment]
![image](https://github.com/decompme/decomp.me/assets/99224452/5487b675-123c-4466-946b-baa8181f45fa)
It seems like this was fixed by aligning the text to the left instead of the right

**Comment by ethteck** [comment]
Ah yeah, this is fixed other than hamster's objection to the entire scratch card not being a link (which I disagree with, but..)

**Comment by mkst** [comment]
I'm going to close this - we want each item to have a link to the platform, scratch, and the preset (if applicable).
