### ISSUE TITLE
[BUG] User dropdown is empty

### ISSUE THREAD

**Issue by marijnvdwerf** [decompme/decomp.me#1143]
User dropdown (top right) on scratch page is empty

<img width="185" alt="image" src="https://github.com/decompme/decomp.me/assets/737603/fb9576d7-5a55-4228-a7a5-24f972b2f586">

Commit: [f9a3e52](https://github.com/decompme/decomp.me/commit/f9a3e527d2f75c5536ce9defa6e6cf0ea0119e8e)

**Comment by ethteck** [comment]
this is known and a fix will be deployed on next site update
