### ISSUE TITLE
[PRESET] Create Compiler Preset Rock Band 3 (Debug)

### ISSUE THREAD

**Issue by TheNathannator** [decompme/decomp.me#1156]
- **Preset Name:** `Rock Band 3 (Debug)`
- **Platform:** `gc_wii`
- **Compiler ID:** `mwcc_43_172`
- **Compiler Flags:** `-nodefaults -nosyspath -gccinc -maxerrors 1 -proc gekko -align powerpc -enum int -fp hardware -pragma "cats off" -pragma "warn_notinlined off" -RTTI on -Cpp_exceptions off -sdata 2 -sdata2 2 -str reuse,pool -func_align 4 -fp_contract on -pragma "merge_float_consts on" -O4,p -inline noauto -lang=c++ -d MILO_DEBUG`

Requesting a separate preset instead of updating the existing one, since we still need to check against retail code on occasion due to inlining.

**Comment by mkst** [comment]
Thanks! The preset has been created, see https://decomp.me/preset/123 or https://decomp.me/api/preset/123 for details.

**Comment by TheNathannator** [comment]
Awesome, thank you!
