### ISSUE TITLE
[BUG] Draggable split lines appear over menu

### ISSUE THREAD

**Issue by marijnvdwerf** [decompme/decomp.me#1173]
It's hard to see, but when you open the side-menu, the draggable split lines overlap the menu. Seems to be a Z-index issue, but I can't find the origin.

**Base state** 
<img width="402" alt="image" src="https://github.com/decompme/decomp.me/assets/737603/07a899d9-3d59-4b5f-b617-b22057496154">

**Menu opened**
<img width="389" alt="image" src="https://github.com/decompme/decomp.me/assets/737603/880e2bac-4d28-4884-b7d4-87409b68c91c">

**Divider locations**
<img width="390" alt="image" src="https://github.com/decompme/decomp.me/assets/737603/5407c7a8-e388-4c16-a5e5-68fae02dc080">

**Comment by mkst** [comment]
Tried to look at this, i can't override the z-index, chrome tells me:
```
The position: static property prevents z-index from having an effect.
Try setting position to something other than static.
```
