### ISSUE TITLE
Add GTE macros for PS1 scratch creation

### ISSUE THREAD

**Issue by Mc-muffin** [decompme/decomp.me#1176]
**Is your feature request related to a problem? Please describe.**
Currently spimdisasm produces macro'd names for GTE COP2 instructions, however these macros are not included in the default asm the site uses when creating scratches so they read as unknown opcodes unless we define the macros ourselves at the top or revert to the less readable COP2 instructions

**Describe the solution you'd like**
Would be nice if the GTE macros were integrated much like the `dlabel` macros are

**Describe alternatives you've considered**
Currently, the required macros can just be copied to the top of the asm at creation time

**Comment by simonlindholm** [comment]
Do you have a link to the macro definitions?

**Comment by Mc-muffin** [comment]
Oh, yeah I forgot to link them, rabbitizer repo has them https://github.com/Decompollaborate/rabbitizer/blob/master/docs/r3000gte/gte_macros.s

**Comment by mkst** [comment]
I was thinking of perhaps splitting the assembly preludes out of this file and read them in at runtime, cos platforms.py is getting a bit on the large side...
