### ISSUE TITLE
[PRESET] Create Compiler Preset "Phantom Hourglass"

### ISSUE THREAD

**Issue by AetiasHax** [decompme/decomp.me#1215]
I would like to create a compiler preset on decomp.me for *The Legend of Zelda: Phantom Hourglass*.

- **Preset Name:** `Phantom Hourglass`
- **Platform:** `nds_arm9`
- **Compiler ID:** `mwcc_30_131`
- **Compiler Flags:** `-O4,p -enum int -char signed -str noreuse -proc arm946e -gccext,on -fp soft -inline on,noauto -Cpp_exceptions off -RTTI off -interworking -sym on -lang=c++`

**Comment by polybiusproxy** [comment]
I suggest for the preset name to be the game's full name (`The Legend of Zelda: Phantom Hourglass` and not `Phantom Hourglass`).

**Comment by AetiasHax** [comment]
> I suggest for the preset name to be the game's full name (`The Legend of Zelda: Phantom Hourglass` and not `Phantom Hourglass`).

I'm okay with either alternative, I just went with the trend of all previous Zelda presets.

**Comment by mkst** [comment]
Done - went with "Phantom Hourglass" to match the other presets (although I do think they should all have the full titles!)

https://decomp.me/preset/128
