### ISSUE TITLE
Libraries options section shouldn't be viewable if the platform has no libraries

### ISSUE THREAD

**Issue by ethteck** [decompme/decomp.me#1221]
![image](https://github.com/decompme/decomp.me/assets/2985314/3e952435-5665-414d-a41f-12136351c09e)

let's just hide this whole area then

**Comment by shubhankar-shandilya-india** [comment]
Hi @ethteck I want to work on this issue. Assign me this issue
Also, tell after opening the webapp where to access this issue and do you want to hide the library section or you want that it should not open the dropdown when no option is available?

**Comment by ethteck** [comment]
Hi! No need to assign you, feel free to just open a PR when ready. It looks like this one just got addressed, but feel free to help out with any future issues. If you have questions, comment on the issue or reach out on discord :)
