### ISSUE TITLE
[PRESET] Create Compiler Preset "Castlevania 64"

### ISSUE THREAD

**Issue by moisesPC** [decompme/decomp.me#1229]
I would like to create a compiler preset on decomp.me for _Castlevania (Nintendo 64)_.

- **Preset Name:** `Castlevania 64`
- **Platform:** `n64`
- **Compiler ID:** `ido7.1`
- **Compiler Flags:** `-O2 -mips2`

**Comment by ethteck** [comment]
https://decomp.me/preset/129 done! :)

**Comment by moisesPC** [comment]
> https://decomp.me/preset/129 done! :)

Hi! It seems that the compiler in the preset is IDO 5.3 rather than IDO 7.1. Could you change it to 7.1? 🙏

**Comment by ethteck** [comment]
whoops, it was set to ido (space) 7.1. fixed

**Comment by moisesPC** [comment]
Thank you!
