### ISSUE TITLE
[PRESET] CreateCompiler Preset Shaun Palmer's Pro Snowboarder

### ISSUE THREAD

**Issue by Daniel-McCarthy** [decompme/decomp.me#1254]
I would like to create/update (delete as applicable) a compiler preset on decomp.me.

- **Preset Name:** `Shaun Palmer's Pro Snowboarder`
- **Platform:** `ps2`
- **Compiler ID:** `mwcps2-2.4-001213`
- **Compiler Flags:** `-version -O0 -opt display -sym on`
Thanks!

**Comment by ethteck** [comment]
Done! https://decomp.me/preset/131
