### ISSUE TITLE
[PRESET] Create Compiler Preset "Castlevania: Symphony of the Night"

### ISSUE THREAD

**Issue by Xeeynamo** [decompme/decomp.me#1257]
I would like to capy a compiler preset on decomp.me.

- **Preset Name:** e.g. `Castlevania: Symphony of the Night`
- **Platform:** e.g. `psp`
- **Compiler ID:** e.g. `mwccpsp_3.0.1_219` (see [Compilers API](https://decomp.me/api/compiler))
- **Compiler Flags:** e.g. `-Op -lang c -sdatathreshold 0`

To not be confused with the existing preset from "Castlevania: Symphony of the Night" for PSX. It is not a mistake I am requesting a new one for PSP.

Thanks :frog:

**Comment by ethteck** [comment]
Dun https://decomp.me/preset/132 :)
