### ISSUE TITLE
[PRESET] Create compiler preset "PaRappa the Rapper 2 (C++)"

### ISSUE THREAD

**Issue by polybiusproxy** [decompme/decomp.me#1261]
I would like to create a compiler preset on decomp.me.
Not to be confused with the current preset, this is for the C++ library of the game that handles rendering, animations, VU1 and other boring stuff.

- **Preset Name:** `PaRappa the Rapper 2 (C++)`
- **Platform:** `ps2`
- **Compiler ID:** `ee-gcc2.9-991111-01`
- **Compiler Flags:** `-O2 -G8 -x c++ -fno-exceptions -gstabs`

Thanks. **\*capybara emoji\***

**Comment by ethteck** [comment]
dun https://decomp.me/preset/133 

![image](https://github.com/decompme/decomp.me/assets/2985314/d5850520-d631-417d-9780-bdefffc6df38)
