### ISSUE TITLE
[PRESET] Update Rock Band 3 Compiler Flags

### ISSUE THREAD

**Issue by TheNathannator** [decompme/decomp.me#1265]
Two presets to update here.

Preset 1:

- **Preset ID:** `114`
- **Preset Name:** `Rock Band 3`
- **Compiler Flags:** `-nodefaults -nosyspath -gccinc -maxerrors 1 -proc gekko -align powerpc -enum int -fp hardware -pragma "cats off" -pragma "warn_notinlined off" -RTTI on -Cpp_exceptions off -sdata 2 -sdata2 2 -str reuse,pool -func_align 4 -fp_contract on -pragma "merge_float_consts on" -O4,s -inline off -lang=c++ -d NDEBUG -d VERSION_SZBE69`

Preset 2:

- **Preset ID:** `123`
- **Preset Name:** `Rock Band 3 (Debug)`
- **Compiler Flags:** `-nodefaults -nosyspath -gccinc -maxerrors 1 -proc gekko -align powerpc -enum int -fp hardware -pragma "cats off" -pragma "warn_notinlined off" -RTTI on -Cpp_exceptions off -sdata 2 -sdata2 2 -str reuse,pool -fp_contract on -pragma "merge_float_consts on" -O4,p -inline noauto -ipa file -lang=c++ -d MILO_DEBUG -d VERSION_SZBE69_B8`

**Comment by mkst** [comment]
**Rock Band 3**
was:
```
-nodefaults -proc gekko -align powerpc -enum int -fp hardware -Cpp_exceptions off -O4,s -inline off -pragma "cats off" -pragma "warn_notinlined off" -maxerrors 1 -nosyspath -fp_contract on -str reuse,pool -func_align 4 -gccinc -sdata 2 -sdata2 2 -pragma "merge_float_consts on" -RTTI on -lang=c++
```
now:
```
-nodefaults -nosyspath -gccinc -maxerrors 1 -proc gekko -align powerpc -enum int -fp hardware -pragma "cats off" -pragma "warn_notinlined off" -RTTI on -Cpp_exceptions off -sdata 2 -sdata2 2 -str reuse,pool -func_align 4 -fp_contract on -pragma "merge_float_consts on" -O4,s -inline off -lang=c++ -d NDEBUG -d VERSION_SZBE69

```

**Rock Band 3 (Debug)**
was:
```
-nodefaults -nosyspath -gccinc -maxerrors 1 -proc gekko -align powerpc -enum int -fp hardware -pragma "cats off" -pragma "warn_notinlined off" -RTTI on -Cpp_exceptions off -sdata 2 -sdata2 2 -str reuse,pool -func_align 4 -fp_contract on -pragma "merge_float_consts on" -O4,p -inline noauto -lang=c++ -d MILO_DEBUG
```
now:
```
-nodefaults -nosyspath -gccinc -maxerrors 1 -proc gekko -align powerpc -enum int -fp hardware -pragma "cats off" -pragma "warn_notinlined off" -RTTI on -Cpp_exceptions off -sdata 2 -sdata2 2 -str reuse,pool -fp_contract on -pragma "merge_float_consts on" -O4,p -inline noauto -ipa file -lang=c++ -d MILO_DEBUG -d VERSION_SZBE69_B8
```

**Comment by TheNathannator** [comment]
Thank you! ❤️
