### ISSUE TITLE
[PRESET] Create/Update Compiler Preset PSP Castlevania: Symphony of the Night

### ISSUE THREAD

**Issue by sozud** [decompme/decomp.me#1271]
I'd like for `-sym on` to be added to the preset to enable line numbers.

Current preset:
```
        {
            "id": 132,
            "name": "Castlevania: Symphony of the Night",
            "platform": "psp",
            "compiler": "mwccpsp_3.0.1_219",
            "assembler_flags": "",
            "compiler_flags": "-Op -lang c -sdatathreshold 0",
            "diff_flags": [],
            "decompiler_flags": "",
            "libraries": [],
            "num_scratches": 77,
            "owner": null
        },
```

- **Preset Name:** Castlevania: Symphony of the Night
- **Preset ID (when updating):** 132
- **Platform:** e.g. `psp`
- **Compiler ID:** e.g. mwccpsp_3.0.1_219
- **Compiler Flags:** e.g. `-Op -lang c -sdatathreshold 0 -sym on`
- **Libraries (if applicable):**  N/A

**Comment by ethteck** [comment]
dun :)
