### ISSUE TITLE
[PRESET] Delete Compiler Preset Dora the Explorer: Barnyard Buddies

### ISSUE THREAD

**Issue by FedericoMilesi** [decompme/decomp.me#1280]
I would like to delete the Dora the Explorer: Barnyard Buddies compiler preset on decomp.me.

Motive: Initially, I wanted to decompile the game to help me get a better grasp of how certain things about PSX games work (like primitive drawing), which I believed would have been easier to learn experimenting with a more basic kind of game than the ones I have been working on so far. While I decompiled a dozen of functions for Dora the Explorer: Barnyard Buddies and requested to create a preset, certain things happened that caused me to abandon the project. So, since I really won't work with it anymore, I would like to have the preset be deleted to cause less noise amongst the other PSX presets that are getting worked on, if that makes sense.

**Comment by mkst** [comment]
I would rather keep the preset in case anyone else wants to work on the game.
