### ISSUE TITLE
[PRESET] Update Compiler Preset F-ZERO X

### ISSUE THREAD

**Issue by inspectredc** [decompme/decomp.me#1287]
I would like to update a compiler preset on decomp.me.

- Preset Name: F-ZERO X
- Preset ID: 135
- Platform: n64

Compiler is currently ido 5.3 but I now believe should be ido 7.1

**Comment by ethteck** [comment]
Changed! Also I noticed the official spelling of  the game has Zero instead of ZERO, so I changed that as well - hope you don't mind

**Comment by inspectredc** [comment]
Sounds good to me, thanks!
