### ISSUE TITLE
[PRESET] Update Compiler Preset PSP Castlevania: Symphony of the Night

### ISSUE THREAD

**Issue by bismurphy** [decompme/decomp.me#1292]
I would like to update (delete as applicable) a compiler preset on decomp.me.

- **Preset Name:** e.g. `Castlevania: Symphony of the Night`
- **Preset ID:** 132
- **Platform:** psp (NOT PS1)
- **Compiler ID:** MWCC 1.3 SP7
- **Compiler Flags:** `-Op -lang c -sdatathreshold 0 -sym on -fl divbyzerocheck`

The existing compiler flags for PSP Symphony of the Night are `-Op -lang c -sdatathreshold 0 -sym on`. I am requesting for `-fl divbyzerocheck` to be added, as this will cause the compiler to emit a block of instructions that seem to always follow a `div` instruction on PSP.

**Comment by mkst** [comment]
This has been done; note that this does not affect existing scratches - only new ones.
