### ISSUE TITLE
[PRESET] Create/Update Compiler Preset Shaun Palmer's Pro Snowboarder

### ISSUE THREAD

**Issue by Daniel-McCarthy** [decompme/decomp.me#1293]
I would like to update a compiler preset on decomp.me.
- **Preset Name:** Shaun Palmer's Pro Snowboarder
- **Preset ID (when updating):** 131
- **Platform:** PS2
- **Compiler ID:** `MWCPS2 2.4 (Built 001213)` (stays the same)
- **Compiler Flags:** `-version -O0,p -opt display -sym on -char unsigned`
- **Libraries (if applicable):**  None

Thank you!

**Comment by ethteck** [comment]
dun
