### ISSUE TITLE
[PRESET] Create Compiler Preset Mario & Luigi: Superstar Saga

### ISSUE THREAD

**Issue by jellees** [decompme/decomp.me#1294]
I would like to create a compiler preset on decomp.me.

- **Preset Name:** e.g. `Mario & Luigi: Superstar Saga`
- **Platform:** `gba`
- **Compiler ID:** `agbcc`
- **Compiler Flags:** e.g. `-mthumb-interwork -Werror -O2 -g`

**Comment by mkst** [comment]
Done! https://decomp.me/preset/138
