### ISSUE TITLE
[PRESET] Create Compiler Preset Sly Cooper and the Thievius Raccoonus

### ISSUE THREAD

**Issue by TheOnlyZac** [decompme/decomp.me#1296]
New preset for Sly 1 decompilation.

- **Preset Name:** e.g. `Sly Cooper and the Thievius Raccoonus`
- **Platform:** e.g. `ps2`
- **Compiler ID:** `ee-gcc2.95.2-273a`
- **Compiler Flags:** `-x c++ -O2 -G0`

**Comment by ethteck** [comment]
dun https://decomp.me/preset/139
