### ISSUE TITLE
[PRESET] Create Compiler Preset for Gran Turismo 2

### ISSUE THREAD

**Issue by ginryuoku** [decompme/decomp.me#1307]
I would like to create a compiler preset on decomp.me.

- **Preset Name:** 'Gran Turismo 2'
- **Platform:** `ps1`
- **Compiler ID:** `psyq4.4`
- **Compiler Flags:** `-O2 -g0 -G0`

**Comment by ethteck** [comment]
all set! https://decomp.me/preset/140
