### ISSUE TITLE
[PRESET] Create/Update Compiler Preset for Disney Infinity 3.0: Gold Edition

### ISSUE THREAD

**Issue by abnormalhare** [decompme/decomp.me#1313]
I would like to create a compiler preset on decomp.me.

- **Preset Name:** `Disney Infinity 3.0: Gold Edition`
- **Preset ID (when updating):** `141`
- **Platform:** `pc`
- **Compiler ID:** `msvc8.0`
- **Compiler Flags:** `/TP /O1`
- **Libraries:** N/A

**Comment by ethteck** [comment]
done! for future reference, if it's a new preset, no need to provide the ID. and the platform is `win32` rather than `pc`

https://decomp.me/preset/141

**Comment by abnormalhare** [comment]
Got it. Thank you!
