### ISSUE TITLE
MSVC8.0 cannot find windows.h

### ISSUE THREAD

**Issue by abnormalhare** [decompme/decomp.me#1314]
**Describe the bug**
Attempting to include `Windows.h` fails when using the new msvc8.0 compiler.

**To Reproduce**
1. Create a new scratch using msvc8.0
2. Go to Context
3. Type `#include <Windows.h>`

**Expected behavior**
Windows.h is include, like in msvc6.0

**Scratches**
https://decomp.me/scratch/zQnyW

**Comment by mkst** [comment]
one for @widberg - there is no WINDOWS.H in the Include directory. 

https://github.com/decompme/compilers/pull/22

**Comment by widberg** [comment]
It looks like Windows.h is in the PlatformSDK directory with the other windows headers https://github.com/widberg/msvc8.0/blob/main/PlatformSDK/Include/Windows.h. I did not set this up to get copied over in the compilers repo, oops. How should I update the compiler definition to have multiple include directories copied?

**Comment by mkst** [comment]
I'll have a crack at it tomorrow, allow for multiple include directories as part of the Jinja templating 😎

**Comment by mkst** [comment]
Should be fixed via https://github.com/decompme/compilers/commit/2ff07e6fee34b0543ede9560cf0ede27a4f4ae03, will need a restart of the site to pull down the new compiler image.

**Comment by mkst** [comment]
This scratch is now compiling successfully with msvc8.0 - thanks for raising the issue!

![image](https://github.com/user-attachments/assets/619a99a9-8efb-47d4-a8fe-73cd55e36d65)
