### ISSUE TITLE
[PRESET] Create/Update Compiler Preset "Shadow of the Colossus"

### ISSUE THREAD

**Issue by joshlory** [decompme/decomp.me#1320]
I would like to create/update (delete as applicable) a compiler preset on decomp.me.

- **Preset Name:** `Shadow of the Colossus`
- **Platform:** `PS2`
- **Compiler ID:** `ee-gcc2.96`
- **Compiler Flags:** `-O2 -g3`

Thank you!

**Comment by mkst** [comment]
Done! https://decomp.me/preset/143
