### ISSUE TITLE
[PRESET] Create Compiler Preset Animal Crossing (GBA Multiboot)

### ISSUE THREAD

**Issue by Prakxo** [decompme/decomp.me#1322]
I would like to create a compiler preset on decomp.me.

- **Preset Name:** `Animal Crossing (GBA Multiboot)`
- **Platform:** `gba`
- **Compiler ID:** `agbcc`
- **Compiler Flags:** `--mthumb-interwork -g3 -O3`

**Comment by ethteck** [comment]
https://decomp.me/preset/144 dun
