### ISSUE TITLE
[PRESET] Create Compiler Preset "Resident Evil: Code Veronica X"

### ISSUE THREAD

**Issue by FedericoMilesi** [decompme/decomp.me#1324]
I would like to create a compiler preset on decomp.me.

- **Preset Name:** `Resident Evil: Code Veronica X`
- **Preset ID (when updating):** `145` 
- **Platform:** `ps2`
- **Compiler ID:** `mwcps2-2.3.3-000906` 
- **Compiler Flags:** `-sdatathreshold 0 -O3,p -sym on`

**Comment by mkst** [comment]
Done! See https://decomp.me/preset/145.
