### ISSUE TITLE
[PRESET] Create Compiler Preset Mega Man X4

### ISSUE THREAD

**Issue by sozud** [decompme/decomp.me#1335]
I would like to create a compiler preset on decomp.me.

- **Preset Name:** `Mega Man X4`
- **Platform:** `ps1`
- **Compiler ID:** `gcc2.7.2-mipsel`
- **Compiler Flags:** `-O2 -G0 -funsigned-char -gcoff -Wa,--aspsx-version=2.56`

See https://decomp.me/scratch/DpAOd for an example
Project here https://github.com/sozud/mmx4

**Comment by mkst** [comment]
Done: https://decomp.me/preset/146.

Note, you'll probably want a `-psx` flavour of that compiler at some point (but one hasnt been made yet - I'll take a look (see [PR](https://github.com/decompals/old-gcc/pull/24) for example). I plan to replace most of the `-mipsel` ps1 GCCs on decomp.me with `-psx` at some point.
