### ISSUE TITLE
[PRESET] Update Compiler Preset for Gran Turismo 2

### ISSUE THREAD

**Issue by ginryuoku** [decompme/decomp.me#1338]
I would like to update a compiler preset on decomp.me.

We're at the point where we've established that enough of the game is in fact C++ that we need C++ enabled for scratches going forward.

- **Preset Name:** `Gran Turismo 2`
- **Preset ID (when updating):** `140`
- **Platform:** `psx`
- **Compiler ID:** `psyq4.4`
- **Compiler Flags:** `-O2 -g0 -G0 -x c++ -fvtable-thunks`

**Comment by mkst** [comment]
Done per https://decomp.me/api/preset/140
```json
{
    "id": 140,
    "name": "Gran Turismo 2",
    "platform": "ps1",
    "compiler": "psyq4.4",
    "assembler_flags": "",
    "compiler_flags": "-O2 -g0 -G0 -x c++ -fvtable-thunks",
    "diff_flags": [],
    "decompiler_flags": "",
    "libraries": [],
    "num_scratches": 228,
    "owner": null
}
```
