### ISSUE TITLE
[PRESET] Create Compiler Preset for Gran Turismo 2 (alternate compiler)

### ISSUE THREAD

**Issue by ginryuoku** [decompme/decomp.me#1339]
I would like to create a compiler preset on decomp.me.

Some TUs within this title use an alternate compiler, presumably to take advantage of code sharing with the GT2000 (later GT3) team. The libraries included inside the mainexe are also 4.6.n. Either way, some symbols and TUs use 2.95.2-style codegen and not 2.8.1-style codegen, so we'd like to define an alternate compiler if possible for these TUs.

- **Preset Name:** `Gran Turismo 2 (2.95.2)`
- **Platform:** `psx`
- **Compiler ID:** `psyq4.6`
- **Compiler Flags:** `-O2 -g0 -G0 -x c++`

**Comment by mkst** [comment]
Done! https://decomp.me/preset/147
