### ISSUE TITLE
[BUG] Wrong instruction has a lower (better) score than the exact matching instruction

### ISSUE THREAD

**Issue by joshlory** [decompme/decomp.me#1352]
**Describe the bug**
I could be missing something obvious... I'm seeing a better match score for `40:    move    v0,zero` than the actual matching instruction `40:    li      v0,1`

**To Reproduce**
1. Go to https://decomp.me/scratch/y3vrf
2. Open the 3-way compare view
3. Change line 37 ("change me") from `return 1` to `return 0`
4. See the issue

**Expected behavior**
Score decreases 

**Screenshots**
<img width="1018" alt="image" src="https://github.com/user-attachments/assets/0e1a7ce3-d9f7-4966-9830-72f09790f150">
<img width="1017" alt="image" src="https://github.com/user-attachments/assets/ef94167b-39d6-4ac8-9e34-92f0a08027b5">

**Scratches**
See repro steps above

**Desktop (please complete the following information if applicable):**
 - OS X
 - Chrome 129

**Comment by joshlory** [comment]
Could be that the re-ordered version is better that the version with more lines matching. So maybe not a bug.

**Comment by mkst** [comment]
It would be an issue for asm-differ, but as you say, the lower score has more correct instructions
