### ISSUE TITLE
[PRESET] Create/Update Compiler Preset "Sonic Rush Adventure"

### ISSUE THREAD

**Issue by UnmarkedFractal** [decompme/decomp.me#1355]
I would like to create a compiler preset on decomp.me for _Sonic Rush Adventure_.

- **Preset Name:** `Sonic Rush Adventure`
- **Platform:** `nds_arm9`
- **Compiler ID:** `mwcc_30_131`
- **Compiler Flags:** `-O4,p -enum int -proc arm946e -gccext,on -fp soft -lang c99 -Cpp_exceptions off -gccinc -interworking -gccdep -MD -g -inline on -str reuse -lang=c -char signed -sym on`

**Comment by mkst** [comment]
Done! https://decomp.me/preset/148
