### ISSUE TITLE
Add Linux (x86/x86_64) Platform

### ISSUE THREAD

**Issue by Mordsdima** [decompme/decomp.me#1361]
**Is your feature request related to a problem? Please describe.**
not related to a problem with decomp me, just will be cool to implement it

**Describe the solution you'd like**
add support for linux elfs (x86 & x86_64)

**Describe alternatives you've considered**
well i can decompile using ghidra but it will harder i guess

**Additional context**
none

**Comment by ethteck** [comment]
Can you explain what's missing on the site currently? We don't support x86_64 yet, but we do support 32-bit x86

**Comment by mkst** [comment]
What project(s) are you working on? Decomp.me is a collaboration tool for matching code, it is not a disassembler (i.e. it's nothing like Ghidra). What compiler(s) are you working with? What is your offline workflow currently?

**Comment by Mordsdima** [comment]
well, mostly decompiling with friend, gcc 3.x, i dont understand you by "offline workflow"

**Comment by Mordsdima** [comment]
maybe i didnt understand that project correct (i just looked and thought what it awesome project to collab decompile with some persons), so, sorry
