### ISSUE TITLE
decomp-permuter built-in tool in the editor

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [decompme/decomp.me#1362]
i can't get the permuter working, i'm using windows and i'm trying to match https://decomp.me/scratch/bBJyP
from my fork of YohannDR's metroid fusion decomp: https://github.com/H-A-M-G-E-R/mf
https://github.com/simonlindholm/decomp-permuter

**Comment by ethteck** [comment]
Would you mind moving this issue into that repo? We don't have the permuter running on the site, so I'm not sure what the title of the issue means here

**Comment by H-A-M-G-E-R** [comment]
this means that you can run the permuter in the site

**Comment by ethteck** [comment]
That's already captured here: https://github.com/decompme/decomp.me/issues/34

if you're having trouble getting the permuter working locally, feel free to ask in discord and folks can help out. but any effort to add the permuter as a tool on the website can be discussed in the already existing issue
