### ISSUE TITLE
[PRESET] Update Compiler Preset for Pokémon Mystery Dungeon: Explorers of Sky

### ISSUE THREAD

**Issue by AnonymousRandomPerson** [decompme/decomp.me#1363]
I would like to update a compiler preset on decomp.me.

Please change the `-enum` flag to `-enum min`.

- **Preset Name:** `Pokémon Mystery Dungeon: Explorers of Sky`
- **Preset ID:** `101`
- **Compiler Flags:** `-O4,s -enum min -proc arm946e -gccext,on -fp soft -lang c99 -char signed -inline on,noauto -Cpp_exceptions off -gccinc -interworking -gccdep -MD -g`

**Comment by ethteck** [comment]
All set!
