### ISSUE TITLE
[PRESET] Create Compiler Preset (Rayman)

### ISSUE THREAD

**Issue by fuerchter** [decompme/decomp.me#1364]
I would like to create a compiler preset on decomp.me.

- **Preset Name:** `Rayman`
- **Platform:** e.g. `ps1`
- **Compiler ID:** `gcc2.5.7-psx`
- **Compiler Flags:** `-O2 -mgas -msoft-float -gcoff -Wa,--expand-div,--aspsx-version=2.08,-mips2`

**Comment by mkst** [comment]
Your wish is my command: https://decomp.me/preset/149.
