### ISSUE TITLE
[PRESET] Update Compiler Preset Shadow Hearts

### ISSUE THREAD

**Issue by RappyPhan** [decompme/decomp.me#1366]
I would like to update a compiler preset on decomp.me.

- **Preset Name:** Shadow Hearts
- **Preset ID (when updating):** 150
- **Platform:** PS2
- **Compiler ID:** mwcps2-2.3.3-000906
- **Compiler Flags:** -lang C++ -O3,p -Cpp_exceptions off -enum min

**Comment by mkst** [comment]
Done!
