### ISSUE TITLE
[PRESET] Create Compiler Preset Championship Surfer

### ISSUE THREAD

**Issue by 1superchip** [decompme/decomp.me#1368]
I would like to create a compiler preset on decomp.me.

- **Preset Name:** `Championship Surfer`
- **Platform:** `win32`
- **Compiler ID:** `msvc6.0`
- **Compiler Flags:** `/Ox /GX /TP /Zd /Gf`

**Comment by mkst** [comment]
Done! https://decomp.me/preset/151
