### ISSUE TITLE
[PRESET] Create/Update Compiler Preset Mega Man X4

### ISSUE THREAD

**Issue by sozud** [decompme/decomp.me#1369]
Could `-msoft-float` be added? Example https://decomp.me/scratch/T1Wfk

- **Preset Name:** `Mega Man X4`
- **Preset ID (when updating):** `146`
- **Platform:** `ps1`
- **Compiler ID:** `gcc2.7.2-psx`
- **Compiler Flags:** `-O2 -G0 -funsigned-char -msoft-float -gcoff -Wa,--aspsx-version=2.56`

**Comment by mkst** [comment]
Done, still no idea why it's necessary because the `cc1` has `-msoft-float` baked in 
```
$ ./cc1 </dev/null
    .file    1 "stdin"

 # GNU C 2.7.2 [AL 1.1, MM 40] Sony Playstation compiled by GNU C

 # Cc1 defaults:
 # -mgas -msoft-float

 # Cc1 arguments (-G value = 8, Cpu = R3000, ISA = 1):
```
