### ISSUE TITLE
[PRESET] Update Compiler Preset Animal Forest (iQue)

### ISSUE THREAD

**Issue by Prakxo** [decompme/decomp.me#1371]
I would like to update a compiler preset on decomp.me.

- **Preset Name:** `Animal Forest (iQue)`
- **Preset ID:** `130`
- **Platform:** `n64`
- **Compiler ID:** `egcs_1.1.2-4`
- **Compiler Flags:** `-mcpu=4300 -mno-abicalls -O2 -g3 -DAF_CN -funsigned-char`

**Comment by mkst** [comment]
Updated, sorry it took so long!
