### ISSUE TITLE
[BUG] Display a message that an object file cannot be decompiled

### ISSUE THREAD

**Issue by 1superchip** [decompme/decomp.me#1372]
**Describe the bug**
When the decompile button is pressed and the scratch is an object file rather than an assembly file, the decompile button opens the decompile tab and spins as if its loading.

**To Reproduce**
1. Go to https://decomp.me/scratch/z3I55
2. Click on `Decompile`
3. The spin icon just spins as if its working

**Expected behavior**
Provide a message that an object file cannot be decompiled rather than endlessly spin as if its working.

**Screenshots**

**Scratches**
https://decomp.me/scratch/z3I55
https://decomp.me/scratch/Otqco
https://decomp.me/scratch/d8G2o

**Comment by ethteck** [comment]
related: #1286
