### ISSUE TITLE
[PRESET] Create Compiler Preset Grand Theft Auto 2

### ISSUE THREAD

**Issue by mouzedrift** [decompme/decomp.me#1375]
I would like to create a compiler preset on decomp.me.

- **Preset Name:** Grand Theft Auto 2
- **Platform:** win32
- **Compiler ID:** msvc4.0
- **Compiler Flags:** /TP /O2 /GX /EHsc

**Comment by ethteck** [comment]
done! https://decomp.me/preset/152
