### ISSUE TITLE
[PRESET] Create compiler preset for "Street Fighter III: 3rd Strike (Anniversary Collection)"

### ISSUE THREAD

**Issue by apstygo** [decompme/decomp.me#1383]
I would like to create a compiler preset on decomp.me.

- **Preset Name:** `Street Fighter III: 3rd Strike (Anniversary Collection)`
- **Platform:** `ps2`
- **Compiler ID:** `mwcps2-3.0b52-030722`
- **Compiler Flags:** `-O0,p -sdatathreshold 128 -sym on -str readonly -fl divbyzerocheck`

**Comment by mkst** [comment]
Done! https://decomp.me/preset/154

**Comment by apstygo** [comment]
Thanks a lot!
