### ISSUE TITLE
[BUG] Decompiler infinitely hangs in certain situations

### ISSUE THREAD

**Issue by Rainchus** [decompme/decomp.me#1385]
**Describe the bug**
The decompile output never appears, infinitely "loading"

**To Reproduce**
1. Open this scratch https://decomp.me/scratch/Zb5FC
2. Click the "decompile" button

**Expected behavior**
It should decompile the assembly but it does not

**Scratches**
[Please provide links to any scratches that demonstrate the problem.](https://decomp.me/scratch/Zb5FC)

**Desktop (please complete the following information if applicable):**
Windows 10
Firefox 132.0.2 (64-bit)

**Additional context**
Seemingly, this doesn't hang for everyone for unknown reasons

**Comment by mkst** [comment]
Closing as dupe of #1372.
