### ISSUE TITLE
Move UI compiler config into general compiler config json file

### ISSUE THREAD

**Issue by ethteck** [decompme/decomp.me#153]
Intead of a separate front-end file. Have the backend return the options as json

**Comment by ethteck** [comment]
I still want to do this, but it should only return the flag names (IDs), rather than the full text descriptions for each one. The reason for this is that it's probably better to keep UI strings on the front-end for eventual support of other languages on the website.

**Comment by nanaian** [comment]
I think we should support the translations in the json file instead just to keep everything in one nice place

**Comment by ethteck** [comment]
I guess that's fine, but it would require storing the user's language in the db and using that to return the appropriate result. cause I'd prefer not to return all languages' strings every request

**Comment by nanaian** [comment]
> I'd prefer not to return all languages' strings every request

Ah, I was assuming we'd hardcode the i18n strings, which we'd obviously split depending on which language is used. You're right
