### ISSUE TITLE
target_asm complexity db field

### ISSUE THREAD

**Issue by nanaian** [decompme/decomp.me#163]
IMO this should be the "worst possible" score value, but other heuristics may be better (like amount of branching)

**Comment by nanaian** [comment]
@ethteck is this `max_score`?

**Comment by ethteck** [comment]
I think this is kinda redundant, yeah. I believe the intention was it to be a function of max_score and maybe other aspects of the code itself, but yeah idk. I'm down to close this for now if you are.

**Comment by nanaian** [comment]
It would be beneficial to populate max_score on scratch creation (e.g. diff against an empty object?) for the 'points' feature we eventually want to have

**Comment by ethteck** [comment]
It is populated on scratch creation, forking, and saving currently (as well as GET to compile)

**Comment by nanaian** [comment]
If the generated source code doesn't compile, is it not set to -1?

**Comment by ethteck** [comment]
Ah I see now. yeah, we'd need to update diff.py to support just one object of input or hackishly give it a stub elf, which seems not ideal

**Comment by ethteck** [comment]
I made #291 for this and I'll handle it
