### ISSUE TITLE
Unnamed scratch names do not appear in prerendered <head>

### ISSUE THREAD

**Issue by nanaian** [decompme/decomp.me#176]
This embed title should be "Untitled scratch | decomp.me":

<img width="300" alt="image" src="https://user-images.githubusercontent.com/9429556/137373154-ce45a230-eb62-48cb-8b33-df2efd4f1705.png">

**Comment by ethteck** [comment]
Getting "Untitled scratch" now, despite the scratch having a name.
<img width="245" alt="image" src="https://user-images.githubusercontent.com/2985314/147773101-1a478b84-7102-4b2d-b2e3-4b9df2d2c0f6.png">

**Comment by nanaian** [comment]
Believe this was fixed in #267

**Comment by ethteck** [comment]
Yee
