### ISSUE TITLE
When creating a scratch, assembler error line numbers do not match the input asm

### ISSUE THREAD

**Issue by bates64** [decompme/decomp.me#179]
This is probably due to ASM_PRELUDE - we either need something akin to `#line` in C or to parse the error messages and change the line numbers. The latter may be more brittle but would allow us to show errors inline in the asm textbox.

**Comment by ethteck** [comment]
discussion here: https://discord.com/channels/897066363951128586/897066363951128590/911713302734864455

**Comment by simonlindholm** [comment]
I wonder if we can use .include or similar compiler flag to include the prelude
