### ISSUE TITLE
Scratch options/context reset after modification

### ISSUE THREAD

**Issue by Drahsid** [decompme/decomp.me#196]
I'm not certain if this problem is relevant to a scratch that the user has made, however, at least when editing other users' scratches, if you modify the context, once you begin editing the source, the editor resets all changes, restoring the original context and source. I tested and can replicate this on Chromium 95.0.4638.69 and Edge 95.0.1020.40.

**Comment by ethteck** [comment]
Hi - yes, this is a known issue with the site and affects the compiler options / other fields as well, not just the context unfortunately. We're working on a fix, but we're short-staffed, so tp speak, so it may take some time. I'll leave this issue open to track the bug.

**Comment by ethteck** [comment]
Fixed in #199 ! We'll re-open if we find this again :)
