### ISSUE TITLE
Address disk space issue

### ISSUE THREAD

**Issue by ethteck** [decompme/decomp.me#207]
The elf_object in `Compilation` takes up a ton of space. We don't need to keep all of them around all the time. I think on bootup of the server, we should clear any elf_object entries that are older than x days, as a starting point

**Comment by nanaian** [comment]
I think entire Compilations last accessed more than n days ago can be deleted, as we always have the information available to regenerate one if required (e.g. someone revisits an old scratch).

**Comment by nanaian** [comment]
Also I think we should do this more than just on bootup, we don't regularly restart the server

**Comment by ethteck** [comment]
`Compilation`s are the only record of changes to a scratch over time, so I'm hesitant to remove the entire object. and yeah agreed, just don't know the best mechanism to run something on an interval. it seems like it'd require a separate thread or something..

**Comment by nanaian** [comment]
> are the only record of changes to a scratch over time

We should definitely consider tracking a git-like history of changes to settings etc

**Comment by nanaian** [comment]
> just don't know the best mechanism to run something on an interval

Probably a cron library. We could implement this as a separate python script and run it as a real cronjob if we wanted also

**Comment by mkst** [comment]
Can you just do it at startup and then every e.g. 1000 requests? Rather than it having to be on a timer?
