### ISSUE TITLE
Diff not updating in certain circumstances

### ISSUE THREAD

**Issue by ethteck** [decompme/decomp.me#219]
From revo:

> https://decomp.me/scratch/OiJu2
> 
> Check "-g" for debug info, then switch the ret = 0; and ret = 1; lines
> 
> I think -g causes the object dump to not update

**Comment by nanaian** [comment]
Hitting the compile button manually after doing this reveals that this is actually caused by the backend returning a 500 Internal Server Error

**Comment by ethteck** [comment]
thanks - yeah as @mkst suggested in chat, it is indeed the diff.py issue with asserting there's only 1 text section. looking into it

**Comment by tfmark** [comment]
related: https://github.com/simonlindholm/asm-differ/pull/66

**Comment by mkst** [comment]
related: https://github.com/simonlindholm/asm-differ/pull/66

**Comment by ethteck** [comment]
Fixed
