### ISSUE TITLE
Add ui options for monaco editor

### ISSUE THREAD

**Issue by ethteck** [decompme/decomp.me#229]
Allow the user to configure basic monaco settings such as turning off autocomplete brackets

https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.IDiffEditorConstructionOptions.html#autoClosingBrackets

**Comment by zbanks** [comment]
tbh I'm kind of surprised Monaco doesn't have any built-in user-facing way of doing this? 
Maybe there's an existing public React component that we could drop in for doing user settings in Monaco? (I didn't find anything in my googling, though :cry: )

**Comment by ethteck** [comment]
that'd be nice, but yeah ...weird that the command palette doesn't have it as an option

**Comment by ethteck** [comment]
moving to codemirror so see ya
