### ISSUE TITLE
Fork tree sorted by match%

### ISSUE THREAD

**Issue by nanaian** [decompme/decomp.me#293]
e.g. https://github.com/decompme/decomp.me/network/members

Including parents

**Comment by nanaian** [comment]
This can go in the about tab

**Comment by nanaian** [comment]
Note that there can be more than one root scratch by creating two new scratches with identical target asm

**Comment by ethteck** [comment]
this is mostly done - we just need a way to choose the sorting method and have that re-sort based on the chosen method

**Comment by nanaian** [comment]
Sorting is done
