### ISSUE TITLE
Scratch export doesn't work as expected

### ISSUE THREAD

**Issue by ethteck** [decompme/decomp.me#326]
https://decomp.me/scratch/r5pf4

No clue on the scope, but it is probably related to the arch

Edit: nevermind, it's happening across the board. should be easy to fix, I think

**Comment by nanaian** [comment]
I'm getting this on Chrome
![image](https://user-images.githubusercontent.com/9429556/151777834-82211889-c188-482f-8988-92c51c6aa72e.png)

**Comment by nanaian** [comment]
Any idea in which commit this was introduced?

**Comment by ethteck** [comment]
no clue :/ I'll try to reproduce locally

**Comment by ethteck** [comment]
ah I got it. it's cause the url here is not a full url, it's the relative part
```
function exportScratchZip(scratch: api.Scratch) {
    const url = `${scratch.url}/export`
    const a = document.createElement("a")
    a.href = url
    a.download = scratch.name + ".zip"
    a.click()
}```
