### ISSUE TITLE
Scratch forks don't copy project_function

### ISSUE THREAD

**Issue by nanaian** [decompme/decomp.me#378]
Also needs migration to fix this for forks that already exist (e.g. https://decomp.me/scratch/nLaas, which forks https://decomp.me/scratch/LkRGS)

**Comment by ethteck** [comment]
srob about it

**Comment by ethteck** [comment]
<img width="238" alt="image" src="https://user-images.githubusercontent.com/2985314/154814679-2d772185-122d-4ae6-a162-349bd2b4a995.png">

**Comment by ethteck** [comment]
![image](https://user-images.githubusercontent.com/2985314/154815023-5fc5a0a2-48db-4f84-9d78-8abb7fcbfbda.png)
