### ISSUE TITLE
Move max_score to Assembly model

### ISSUE THREAD

**Issue by nanaian** [decompme/decomp.me#379]
This will also allow us to point to an Assembly from a ProjectFunction and thereby sort ProjectFunctions by their assembly.max_score/complexity (#370)

**Comment by ethteck** [comment]
I started working on this, and then I realized that various diff settings such as the diff label and the diff stopping point (controlled by --disassemble=xyz) affect the max score. Theoretically, scratches may have different diff settings for the same Assembly. 

We could get around this by storing these things inside the Assembly and "forking" the Assembly objects as we do the Scratch ones...but idk

**Comment by ethteck** [comment]
I also don't think we need to be processing all the raw asm in an entire project to be able to produce metadata like this. Imo the tool(s) that add this metadata to the site should be able to provide it themselves
