### ISSUE TITLE
code match reported incorrectly

### ISSUE THREAD

**Issue by StanHash** [decompme/decomp.me#394]
https://decomp.me/scratch/WuzME reports a 100% match while the output asm still differs from the input in one spot (incorrect branch at a8: `bne.n fa` vs. `bne.n b4`).

**Comment by ethteck** [comment]
Huh, nice find! This is a problem with asm_differ, so the issue is best reported there if you don't mind. https://github.com/simonlindholm/asm-differ

**Comment by StanHash** [comment]
oh sorry I'm not familiar with how this is structured, I'll report it there

**Comment by ethteck** [comment]
no worries at all :)
