### ISSUE TITLE
Hide Problems panel

### ISSUE THREAD

**Issue by MonsterDruide1** [decompme/decomp.me#395]
The recently added panel for displaying compiler warnings and errors currently has no way of hiding. After taking a look at the warnings, you might want to ignore them, hiding the panel until "more issues" happen - which is not possible at the moment.

**Comment by nanaian** [comment]
This necessitates a bottom toolbar that can be used to summon the problems panel back

**Comment by ethteck** [comment]
[fa9bab2](https://github.com/decompme/decomp.me/commit/fa9bab2ec61531cbaac163fcffc2b91242b4cbc4) sadly this didn't work right on the live site (see discord #help for details)
