### ISSUE TITLE
Rename scratch/edit assembly

### ISSUE THREAD

**Issue by mid-kid** [decompme/decomp.me#414]
It'd be great to be able to edit the assembly of a scratch, or its name, after it's created.

Alternatively, simply allowing one to be deleted would help a ton as well.

**Comment by ethteck** [comment]
Scratches can be renamed - just click the name at the top of the page and
edit it. As for assembly, it's a request we get a lot, but there are many
ramifications that make it difficult.

There's currently an issue to delete (/archive) scratches, I believe

**Comment by nanaian** [comment]
See #308

**Comment by ethteck** [comment]
Gonna close since everything else has been touched on, and I made a new issue dedicated to editing target asm in #415
