### ISSUE TITLE
CompilerFlags component takes an abnormal time to render

### ISSUE THREAD

**Issue by nanaian** [decompme/decomp.me#417]
In React Devtools profiler:

<img width="648" alt="image" src="https://user-images.githubusercontent.com/9429556/160866623-863d2ddc-612a-49f1-800f-2abc779e9952.png">

Probably due to schema system React can't cache the render so the entire DOM is remade every time

**Comment by nanaian** [comment]
This appears fixed now

**Comment by ethteck** [comment]
fixed sometime
