### ISSUE TITLE
Use CompilerConfig model in Scratch model

### ISSUE THREAD

**Issue by bates64** [decompme/decomp.me#439]
A little refactor.
Make sure to not break the existing create scratch endpoint's interface (#148 would help here!)

**Comment by nanaian** [comment]
@ethteck did we get anywhere with this

**Comment by ethteck** [comment]
I've been working on it

**Comment by ethteck** [comment]
This isn't needed anymore since we store Presets in the backend, which are essentially CompilerConfig
