### ISSUE TITLE
Show error/warning squiggles on sourcecode + problems view

### ISSUE THREAD

**Issue by bates64** [decompme/decomp.me#44]
The frontend should attempt to parse warnings/errors emitted by the compiler on specific lines and display warning/error squiggles on those lines. We should also show warnings/errors in their own box similar to vscode, as functions can get lengthy,

See https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html#setmodelmarkers

**Comment by nanaian** [comment]
Note that different compilers report errors/warnings differently. We only need to grab look for "src.c" and the line number at a base level; we could potentially grab the column number with IDO also.

Gcc281 (only lines 2 and 5 are important)
```
src.c: In function `func':
src.c:2: `non_existent_t' undeclared (first use in this function)
src.c:2: (Each undeclared identifier is reported only once
src.c:2: for each function it appears in.)
src.c:2: parse error before `foo'
```

Ido71 and Ido53:
```
cfe: Error: src.c, line 2: Syntax Error
     non_existent_t foo;
 -------------------^
```

**Comment by nanaian** [comment]
Opinions wanted - should be ignore warnings originating from the context?

**Comment by ethteck** [comment]
I think this is basically accomplished via the language server
