### ISSUE TITLE
Support font ligatures

### ISSUE THREAD

**Issue by ribbanya** [decompme/decomp.me#531]
Now that we can set our own fonts, it would be nice to have ligatures as an option. From cursory research, it seems as easy as [toggling a CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures).

**Comment by nanaian** [comment]
Can you try enabling `font-variant-ligatures: normal` or otherwise in your browser/OS combination to test this? It works for me as-is on Chrome and Safari macOS:
<img width="689" alt="image" src="https://user-images.githubusercontent.com/9429556/190297212-c480620e-b7da-4a98-92b2-03783f5f80ea.png">

**Comment by ribbanya** [comment]
After messing with the fonts on my system the ligatures are working for me. Thanks for the help!
