### ISSUE TITLE
Have Deployment Robort build a changelog

### ISSUE THREAD

**Issue by ethteck** [decompme/decomp.me#551]
Currently, Deployment Robort just tells us which commit we are coming from and which we're going to. However, we can probably provide more information, showing a brief changelog based on the commits in the series.

This should be fairly trivial - just get the first line or so of each commit from where we start to where we're going. We already have the commit hashes, so this should be doable with some bash / git commands. 

If a snippet is provided, I'll add it to the deployment script.

**Comment by ethteck** [comment]
<img width="255" alt="image" src="https://user-images.githubusercontent.com/2985314/191740341-f4a59cef-36b3-4fe7-821e-291c055931ca.png">

We have the variables in our update script as `$OLD_HASH` and `$NEW_HASH`

**Comment by nanaian** [comment]
Also, we should have him send a message when deployment starts (and potentially delete it after deployment is done)

**Comment by ethteck** [comment]
I did it
