### ISSUE TITLE
Scratch ui takes a long time to load on scratches with very large contexts

### ISSUE THREAD

**Issue by ethteck** [decompme/decomp.me#593]
Reported by @EpochFlame on Firefox, but I've noticed it too on Chrome as well.

I don't think this is purely a limitation of network speed, because this didn't used to manifest like this

example scratch: https://decomp.me/scratch/xSD1k

<img width="601" alt="image" src="https://user-images.githubusercontent.com/2985314/205992083-30dfd352-f502-45f9-9f9b-e21cdb749c61.png">

The request it's waiting on is the scratch api call, but there's only 640 kb of data to send and it takes a long time to recieve it.

**Comment by ethteck** [comment]
During the waiting period, I have a window that looks like this (no loading bar, no indication of loading, a very long delay before anything appears on screen) 
<img width="965" alt="image" src="https://user-images.githubusercontent.com/2985314/205992956-2cd1c0d1-b31d-42c3-b950-99768837c37c.png">

**Comment by EpochFlame** [comment]
worth noting it also does the above on iphone safari

**Comment by nanaian** [comment]
Looks like this issue is in the ServiceWorker; I thought I removed it but I guess I failed
Likely cause of #595 too
