### ISSUE TITLE
Hard refreshes (cache reloads) are sometimes necessary when content changes on the site

### ISSUE THREAD

**Issue by ethteck** [decompme/decomp.me#597]
This seems to happen any time we update compilers / presets / etc. Happened most recently in #594

**Comment by nanaian** [comment]
I don't know if we should consider this a bug, a site update such as updated compilers seems like it should require one

**Comment by nanaian** [comment]
No cache headers should be causing this

https://decomp.me/api/compilers

Possible nextjs issue

**Comment by ethteck** [comment]
adding more labels / commenting since this is still a problem and really affects usability of the site

**Comment by nanaian** [comment]
would be helpful to find a way to reliabily reproduce this- not entirely sure what the issue is. maybe `api.getCached`?
