### ISSUE TITLE
Invalid scratch slugs lead to ugly 404 pages

### ISSUE THREAD

**Issue by ethteck** [decompme/decomp.me#655]
https://decomp.me/scratch/eYSpD (For example)

<img width="612" alt="image" src="https://user-images.githubusercontent.com/2985314/211530173-537704ee-b20a-48e1-b5e4-72b97c561ff1.png">

**Comment by nanaian** [comment]
Surprised that `app/error.tsx` isn't triggered at this route - I could be misunderstanding the docs, or it could be a Next.js beta bug...
Hopefully placing an `app/scratch/[slug]/error.tsx` that reexports the aforementioned Error should fix it.

**Comment by nanaian** [comment]
This _is_ a Next.js bug! https://github.com/vercel/next.js/issues/45385
Looks like they've deprecated `head.tsx` in favour of [exporting a `metadata` object from the page](https://beta.nextjs.org/docs/guides/seo), will use that instead

**Comment by nanaian** [comment]
Unblocked once #705 is merged
