### ISSUE TITLE
"Unkown compiler" errors don't get properly transformed / handled on the frontend

### ISSUE THREAD

**Issue by ethteck** [decompme/decomp.me#665]
https://decomp.me/scratch/S4Dzb

on the backend:
<img width="595" alt="image" src="https://user-images.githubusercontent.com/2985314/214756545-1ece7f53-4ea9-47e1-a22b-fcd5970ed287.png">

**Comment by nanaian** [comment]
Looks like Unknown compiler should be an APIException instead of a ValueError

**Comment by nanaian** [comment]
Actually, this is indicative of an integrity problem: why is there a scratch with an invalid compiler?

**Comment by ethteck** [comment]
I haven't figured that out yet, because this compiler should exist: https://github.com/decompme/decomp.me/blob/main/backend/coreapp/compilers.py#L278

**Comment by ethteck** [comment]
lol

**Comment by ethteck** [comment]
it dun https://github.com/decompme/decomp.me/commit/002b300d68834a2715004c827be5d06780747fae & https://github.com/decompme/decomp.me/commit/6889302d76599cb864acb717e9ca5ca1c78d7c23
