### ISSUE TITLE
'Create Scratch' button lacks top margin

### ISSUE THREAD

**Issue by marijnvdwerf** [decompme/decomp.me#673]
Minor visual bug. There should probably be some spacing between the button and the input area.

<img width="215" alt="image" src="https://user-images.githubusercontent.com/737603/217009054-ee426611-30c4-4094-9361-30d7e101dbfc.png">

**Comment by EidanGar** [comment]
Hello, I'd like to claim this issue. Would 1rem work for you for the margin-top? And where can I find the Create Scratch button?

**Comment by nanaian** [comment]
> Could you post a screenshot after your change and we can see if it looks good?

Can just submit a PR and view the preview deployment

**Comment by ethteck** [comment]
true that true 🐱

**Comment by EidanGar** [comment]
> Hi! Could you post a screenshot after your change and we can see if it looks good?
> 
> I believe the page you want is new.tsx

I found the file, but I can't find a button with the text "Create scratch". I was only able to find an AsyncButton with the text "Create Project" and a GitHubLoginButton.

**Comment by ethteck** [comment]
Ah, I was wrong - the page is NewScratchForm.tsx. I recommend setting the project up in an IDE - it makes searching this stuff a lot easier.
