### ISSUE TITLE
User profile page GitHub link is misaligned

### ISSUE THREAD

**Issue by marijnvdwerf** [decompme/decomp.me#686]
The GitHub link appears to be left aligned based on the username, instead of being centred horizontally.

![IMG_3897](https://user-images.githubusercontent.com/737603/220568368-50f3a5e6-2616-4419-81b8-45e7dfc91ce4.jpeg)

**Comment by nanaian** [comment]
This is a result of the non-mobile layout being left-aligned:
<img width="808" alt="image" src="https://user-images.githubusercontent.com/9429556/220574742-922b6252-03ae-41a8-b2a2-fa172b6d9c9f.png">

**Comment by shubhankar-shandilya-india** [comment]
Hi @marijnvdwerf, I have started working on it.
