### ISSUE TITLE
Anonymous user pages

### ISSUE THREAD

**Issue by ethteck** [decompme/decomp.me#687]
They used to exist, and now they don't, or at least the links are gone. reported by @NWPlayer123 and I've seen others request this back as well

**Comment by ethteck** [comment]
people seem to have thinked so...but maybe not?

**Comment by nanaian** [comment]
AFAIK there's no API for accessing the scratches or profiles of anonymous users, so gonna tag this with backend too.

On another note I'm personally not in favour of this feature, surely if someone wants to have their scratches listed they would log in? What are the use-cases of this?

**Comment by NWPlayer123** [comment]
To find scratches if you haven't logged in, the convo we had was that someone had worked on a bunch of Animal Crossing functions while not logged in and it was annoying to track down, would've been much easier if anonymous user pages worked

and yeah, it would be nice if everyone logged in but it logs me out constantly, and some people don't want to go through the hassle of checking if they're logged in every time

**Comment by ethteck** [comment]
the fact that we get logged out often is something we should fix too. I've noticed that but unfortunately don't know how to consistently reproduce it or anything

**Comment by mkst** [comment]
Do we still need this functionality, or is it enough to track down scratches based on the preset / platform pages?

**Comment by ethteck** [comment]
yeah, we probably don't need this given what you said. if no one squeaks up, I'll close it soon

**Comment by bates64** [comment]
Agree, it’s somewhat against the point of anons to have pages that link their scratches together
