### ISSUE TITLE
Rapid "compiling..." loop in yarn dev when navigating to the profile page from a scratch

### ISSUE THREAD

**Issue by ethteck** [decompme/decomp.me#712]
![image](https://user-images.githubusercontent.com/2985314/227715417-25ceed81-200e-43ba-a428-6d01ea409d68.png)

**Comment by nanaian** [comment]
I could be wrong but IIRC I started noticing this behaviour after the shopify worker plugin was introduced in #605

**Comment by ethteck** [comment]
@zbanks would you be willing to look into this maybe?

**Comment by ethteck** [comment]
I had a brain moment, I meant to tag @ConorBobbleHat (sorry zach)
