### ISSUE TITLE
Make the website not implode when it goes down

### ISSUE THREAD

**Issue by ethteck** [decompme/decomp.me#719]
<img width="437" alt="image" src="https://user-images.githubusercontent.com/2985314/228131920-051c2ce2-1943-4f24-89b6-4d9e5db74b58.png">
Pages should hopefully still stay up, and we should maybe warn the user to not navigate away while the site is updating. Instead, pages insatntly change to this yucky error, and so all progress is lost. very unfortunate if you're editing a scratch

**Comment by nanaian** [comment]
#617

**Comment by nanaian** [comment]
Duplicate of #617
