### ISSUE TITLE
Last metadata separator on Scratches page lacks spacing

### ISSUE THREAD

**Issue by marijnvdwerf** [decompme/decomp.me#724]
The last `&middot;` doesn't have any space on the right. Issue seems to be that `.ScratchList_metadata` has `display: flex`.

<img width="456" alt="image" src="https://user-images.githubusercontent.com/737603/229734539-1b0ee332-2759-4e5d-a36c-9f51caec8a42.png">

<img width="831" alt="image" src="https://user-images.githubusercontent.com/737603/229734404-e47a2ab4-bd54-4678-ad86-bad36a8ad8ac.png">

**Comment by mkst** [comment]
Closing as I believe this is fixed:

![image](https://github.com/decompme/decomp.me/assets/22226349/42d1678a-73a2-42ba-9b1b-c86ea9516283)
