### ISSUE TITLE
Contrast on fully-matching indicator in light mode is wrong

### ISSUE THREAD

**Issue by marijnvdwerf** [decompme/decomp.me#750]
<img width="149" alt="image" src="https://github.com/decompme/decomp.me/assets/737603/0bef9c72-0920-4b84-b86c-f619ada2a33b">

The checkmark should always be white (or dynamically determine the best contrasting colour for the accent colour?)

**Comment by nanaian** [comment]
Should be able to just change the checkmark colour to `var(--g300)` or so

**Comment by marijnvdwerf** [comment]
aren't the g-colours dynamic? e.g. black in dark mode is white in light mode?
