### ISSUE TITLE
Favicon appears boxed in Google results

### ISSUE THREAD

**Issue by marijnvdwerf** [decompme/decomp.me#759]
<img width="339" alt="image" src="https://github.com/decompme/decomp.me/assets/737603/100ee8f8-4a89-4926-9a98-fe5851606379">

**Comment by mkst** [comment]
The png used is this, which has a grey background:
```data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABwAAAAcCAMAAABF0y+mAAAAS1BMVEUoLzErMjUcLiBOI3FkIZGAGrvSjfvat/WaHuFDK13MiPTZ4NSwtq7r1/uSCNqPlo+VH9kuNTkxOD2tUuW2YOu7bOuIYKNcSHCudtFX/bu7AAAA2UlEQVR4AcXNBZIEIQxAUVyXDKH1/iddIDBetvrb+1Uq7H/j83ivLXp7HBJSSdGQXoiJuNDGOiVqylmjBScm9SF+JFBaK0gfMXjGiftNhnhJ4HLOkC4xyLm/3xFsyqNkAekvIRcKYCKAErw35r3Ldzl/hyh0fkiLu8lCg7qeNFpuyOQzSjYR+0pwy7pt65KhL8WJnK3LFkzombAtK+OIA1HsQ4bvAisi41iR36shq7E22PQ4zeg8yPhE5EywY68d9QWpieStJqUMHFYK/SotfMJm9w18S+Wbk59b+hlTT5ghBQAAAABJRU5ErkJggg==```

I guess Google have done something with their formatting, as it's now in a circle:

![image](https://github.com/decompme/decomp.me/assets/22226349/aea4dbf2-a0aa-4e10-9d05-bb42b645d621)

So the question is: should the favicon just be the frog with a transparent (or white) background?

**Comment by marijnvdwerf** [comment]
I guess Google uses this image from the [manifest](https://decomp.me/manifest.json): 

![icon](https://decomp.me/purplefrog-bg-512.png)

**Comment by shubhankar-shandilya-india** [comment]
HI @bates64 @marijnvdwerf I am willing to work on this issue. Could you please suggest what I can do to resolve this issue ?

**Comment by bates64** [comment]
Hi Sushankar, I reckon the best thing to do is change the image in the manifest to have a light background. Then on Google it will look like the GitHub result that Mark posted.

**Comment by shubhankar-shandilya-india** [comment]
Hi @bates64 @marijnvdwerf 
should I replace this code "src": "purplefrog-512.png" in the manifest.json code it with this image 

            
![68747470733a2f2f6465636f6d702e6d652f707572706c6566726f672d62672d3531322e706e67 (1)](https://github.com/decompme/decomp.me/assets/78155393/973a8a83-f592-4da5-92da-6dd16190f4f0)

**Comment by mkst** [comment]
Should generate a png from an svg to ensure its nice and crisp

**Comment by shubhankar-shandilya-india** [comment]
should i use general web tools to generate one from svg or there is any other method @mkst

**Comment by mkst** [comment]
![frog-512-white](https://github.com/decompme/decomp.me/assets/22226349/aca0fc85-82e2-46ec-a759-f994945b2365)
![frog-512-transparent](https://github.com/decompme/decomp.me/assets/22226349/b36cc89d-c371-4541-b254-16e80b6626bf)

I'm not sure if they are going to be optimised by the upload process. So here's a zip with them in:

[frog-512.zip](https://github.com/decompme/decomp.me/files/15198917/frog-512.zip)

**Comment by shubhankar-shandilya-india** [comment]
Ok so i will replace the "src": "purplefrog-512.png" with this white background image in manifest.json

**Comment by mkst** [comment]
Sounds good to me!
