### ISSUE TITLE
Credits page avatars shrink on long names

### ISSUE THREAD

**Issue by marijnvdwerf** [decompme/decomp.me#762]
![image](https://github.com/decompme/decomp.me/assets/737603/e5a41c85-e28b-4f04-9c9c-580e65814434)

**Comment by marijnvdwerf** [comment]
Might be an idea to not have them as columns, but have them wrap, just like the buttons below? Would need some more spacing to make it feel less awkward.

<img width="674" alt="image" src="https://github.com/decompme/decomp.me/assets/737603/10a97d54-4ecc-4696-a306-a907576ebde4">

**Comment by nanaian** [comment]
I like this, like flexbox space-between or something. Should make sure everything incl the images are `flex-shrink: 0` to fix this

**Comment by marijnvdwerf** [comment]
<img width="709" alt="image" src="https://github.com/decompme/decomp.me/assets/737603/852c248e-6983-4bd2-9e22-e00184edafae">

I played around in devtools a bit. Something like this looks a lot calmer to me. I added a `column-gap: 8px; row-gap: 4px; margin: 0 -8px;` to the container, and removed the @ signs. Sorted by people with/without avatars for a more structured look.

Example with @-signs kept:
<img width="689" alt="image" src="https://github.com/decompme/decomp.me/assets/737603/fbb88f6c-1c05-4913-81a9-04d7c7a07c09">
