### ISSUE TITLE
`JSON.parse` runtime exception

### ISSUE THREAD

**Issue by ribbanya** [decompme/decomp.me#782]
I keep encountering the following error:
![image](https://github.com/decompme/decomp.me/assets/5190964/d3b26bde-51a2-43d7-8730-c2fa9c24cc4c)

Seems to occur on the entire website, but only on my main Firefox profile. A Private Browsing window doesn't experience it.

I have one cookie that's 16.4 MB but I don't want to leak anything. Let me know what would be helpful.

```
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.0
```

**Comment by mkst** [comment]
Does it happen on a particular scratch? Is it reproducible or intermittent? Is there anything interesting in the developer console (hit F12, select console).

This usually happens when the backend returns something that isn't JSON (i.e it had an error), but interesting if you're experiencing different behaviour in private browsing. 

Maybe related to local storage (i.e. bad data in a scratch context?). Would be good to get to the bottom of this rather than just asking you to clear site cookies/data.

**Comment by ribbanya** [comment]
It seems to occur on every scratch, and the homepage, etc. Initially the page loads and then is replaced with the exception.

Turns out there's quite a bit going on in the console.
```
GET https://decomp.me/api/user 1185-1963ad663e0d73ef.js:1:9221
GET https://decomp.me/api/stats 1185-1963ad663e0d73ef.js:1:9221
GET https://decomp.me/api/user/scratches?page_size=16 1185-1963ad663e0d73ef.js:1:9221
GET https://decomp.me/api/scratch?page_size=30 1185-1963ad663e0d73ef.js:1:9221
TypeError: can't convert undefined to object .excmds_content.generated.ts:2097:27
SyntaxError: JSON.parse: unexpected character at line 2 column 1 of the JSON data 8944-61dca2a8f1727bdc.js:1:4476
    NextJS 87
Error boundary caught an error: SyntaxError: JSON.parse: unexpected character at line 2 column 1 of the JSON data 
Object { componentStack: "\nZ@https://decomp.me/_next/static/chunks/5638-abfb86dc06a58e63.js:1:5098\nli\nul\nnav\nY@https://decomp.me/_next/static/chunks/5638-abfb86dc06a58e63.js:1:9078\no@https://decomp.me/_next/static/chunks/app/(navfooter)/error-adcfed0096a81d2d.js:13:2627\nE@https://decomp.me/_next/static/chunks/8944-61dca2a8f1727bdc.js:1:21386\ni@https://decomp.me/_next/static/chunks/8944-61dca2a8f1727bdc.js:1:30635\nc@https://decomp.me/_next/static/chunks/8944-61dca2a8f1727bdc.js:1:30702\no@https://decomp.me/_next/static/chunks/8944-61dca2a8f1727bdc.js:1:28793\nl@https://decomp.me/_next/static/chunks/8944-61dca2a8f1727bdc.js:1:28920\nS@https://decomp.me/_next/static/chunks/8944-61dca2a8f1727bdc.js:1:23024\nl@https://decomp.me/_next/static/chunks/8944-61dca2a8f1727bdc.js:1:16468\ni@https://decomp.me/_next/static/chunks/8944-61dca2a8f1727bdc.js:1:17090\nj@https://decomp.me/_next/static/chunks/8944-61dca2a8f1727bdc.js:1:20217\nP@https://decomp.me/_next/static/chunks/8944-61dca2a8f1727bdc.js:1:21080\nl@https://decomp.me/_next/static/chunks/8944-61dca2a8f1727bdc.js:1:31973\nR@https://decomp.me/_next/static/chunks/8944-61dca2a8f1727bdc.js:1:23400\nbody\nhtml\ni@https://decomp.me/_next/static/chunks/8944-61dca2a8f1727bdc.js:1:30635\nc@https://decomp.me/_next/static/chunks/8944-61dca2a8f1727bdc.js:1:30702\no@https://decomp.me/_next/static/chunks/8944-61dca2a8f1727bdc.js:1:28793\nl@https://decomp.me/_next/static/chunks/8944-61dca2a8f1727bdc.js:1:28920\nS@https://decomp.me/_next/static/chunks/8944-61dca2a8f1727bdc.js:1:10670\nl@https://decomp.me/_next/static/chunks/8944-61dca2a8f1727bdc.js:1:16468\ni@https://decomp.me/_next/static/chunks/8944-61dca2a8f1727bdc.js:1:17090\nR@https://decomp.me/_next/static/chunks/8944-61dca2a8f1727bdc.js:1:13869\nC@https://decomp.me/_next/static/chunks/8944-61dca2a8f1727bdc.js:1:5267\nD\nA@https://decomp.me/_next/static/chunks/8944-61dca2a8f1727bdc.js:1:5639" }
8944-61dca2a8f1727bdc.js:1:4476
SyntaxError: JSON.parse: unexpected character at line 2 column 1 of the JSON data 8944-61dca2a8f1727bdc.js:1:4476
    NextJS 101
SyntaxError: JSON.parse: unexpected character at line 2 column 1 of the JSON data 8944-61dca2a8f1727bdc.js:1:4476
Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 2 column 1 of the JSON data
The resource at “https://decomp.me/_next/static/css/f9e3deca92ee0149.css” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. decomp.me
```

I'm not sure how to copy the local storage data, but it might be an unescaped value in the `new_scratch_context` or something?
![image](https://github.com/decompme/decomp.me/assets/5190964/db803800-0cba-4df2-8985-911c56fd3647)

**Comment by ribbanya** [comment]
https://gist.github.com/ribbanya/32c052463c128b88d2690c0781a99a95

**Comment by mkst** [comment]
Another thing to check is whether within the Network tab (developer tools again) you can find the entry that should be JSON but isn't, maybe one of the POST or GET requests. This one is a bit trickier to explain though!

**Comment by ribbanya** [comment]
https://decomp.me/api/scratch?page_size=30 and https://decomp.me/api/stats returned valid JSON.  https://decomp.me/proxy/api/event returned `ok`.

https://decomp.me/api/user and https://decomp.me/api/user/scratches?page_size=16 both returned:
```html
<!doctype html>
<html lang="en">
<head>
  <title>Server Error (500)</title>
</head>
<body>
  <h1>Server Error (500)</h1><p></p>
</body>
</html>
```

Nothing else jumps out at me but let me know if I should inspect anything else.
![image](https://github.com/decompme/decomp.me/assets/5190964/35904575-58a3-413a-8811-e55e490c0e0c)

**Comment by ConorBobbleHat** [comment]
Some more observations from poking around with the api:
- `https://decomp.me/api/users/ribbanya` returns an internal server error even in a private session unaffiliated with any user
- iterating through `https://decomp.me/api/scratch` using the `next` field produces the same error after six iterations (as I write this)

drawing a line between the two - it seems like the backend scratch serializer is goofing up on a scratch that was created about five to seven days ago? (pure guesswork based on the dates from the last `/api/scratch` page that loaded)

**Comment by ribbanya** [comment]
Oh, interesting, I was messing around with creating scratches via the API at around that time.

**Comment by ConorBobbleHat** [comment]
Sorry! I hadn't had my coffee yesterday writing that - `/api/users` doesn't list scratches 🤦. It's the profile serializer that's having a bad time.
A long shot, but - I don't suppose you revoked decomp.me's access to your github account at any point in the last week?

**Comment by ribbanya** [comment]
Oh! That must be what it was. My tokens were recently wiped as a precaution. Should I just clear cookies and log in again?

**Comment by ConorBobbleHat** [comment]
Just tested with my account on the live site - that should do the trick 👍

**Comment by ribbanya** [comment]
Yep, that fixed it. Thank you for the help.

I'll let someone else close this in case you want to fix up the error handling.
