### ISSUE TITLE
Add support for psyq 4.7

### ISSUE THREAD

**Issue by matty45** [decompme/decomp.me#793]
Some games such as "Hot Wheels Turbo Racing" use this version of the sdk.

**Comment by mkst** [comment]
Can you confirm what versions of CC1PSX.EXE / ASPSX.EXE are in PSYQ 4.7? SDK - and can you provide a link? The only zip I've seen for version 4.7 seems to just contain the library files rather than any compilers.

**Comment by matty45** [comment]
Seems there is a possibility that 4.7 does not contain any compilers by default but can be used with the 4.6 compilers just fine.
[Source](https://www.psxdev.net/forum/viewtopic.php?t=1213)

**Comment by mkst** [comment]
Cool, closing the ticket.

**Comment by matty45** [comment]
Oh wait, there are some extra files that are not in the psxdev.net archive that are in this: https://archive.org/details/cave_barn_studios_flo

**Comment by mkst** [comment]
Are you working on decompiling a PSX game and have a "PSYQ 4.7" compiler locally that is missing from decomp.me? I'm trying to determine whether there is a problem to be solved here...

**Comment by mkst** [comment]
I only found gcc 2.7.2 in that iso.
```
mark@carbon:/media/mark/FLOMAMA$ find . -name "CC1PSX.EXE" 
./progtools/PSSN/BIN/CC1PSX.EXE
./progtools/PSSN/BIN/DOS/CC1PSX.EXE
./Psx/BIN/DOS/CC1PSX.EXE
./ps/Psx/BIN/CC1PSX.EXE
./ps/Psx/BIN/DOS/CC1PSX.EXE
./ps/pssn/BIN/CC1PSX.EXE
./ps/pssn/BIN/DOS/CC1PSX.EXE
```
