### ISSUE TITLE
MWCCARM (DS compiler) memset and memcpy optimisations not applying

### ISSUE THREAD

**Issue by red031000** [decompme/decomp.me#795]
This is something of a backend issue

When compiling locally, using the same context and exact same code memset and memcpy inlines and optimises, however on decomp.me, it always calls the functions

You can force it to optimise using \_\_builtin\_clear and \_\_memcpy, however, this is somewhat inconveniet.

I have no idea what is triggering the inlining, and I have no idea if this can even be fixed to be honest, but I'm creating the issue just incase it can be

**Comment by red031000** [comment]
closing this, as I jumped the gun a bit, it's inconsistent even locally, so likely a compiler setting or a specific trigger hasn't been reached

**Comment by red031000** [comment]
looking more into it, this requires the definitions of memset and memcpy to be in string.h *exactly*, and with the way the site is setup that's sadly not going to be possible

**Comment by simonlindholm** [comment]
That's hilarious. Does it work with `#line 1 "string.h"`?

**Comment by red031000** [comment]
haven't tried that, I can take a look at it
