### ISSUE TITLE
ido 6 seems broken

### ISSUE THREAD

**Issue by ethteck** [decompme/decomp.me#814]
@LLONSIT making this so I don't lose track. let me know if you're able to debug this or if there's anything I can do to help

**Comment by mkst** [comment]
Dupe of https://github.com/decompme/decomp.me/issues/721 or no?

**Comment by LLONSIT** [comment]
> @LLONSIT making this so I don't lose track. let me know if you're able to debug this or if there's anything I can do to help
Currently, I can't debug the problem, but a possible solution that I'm going to try is updating the compiler package binaries because I saw that some binaries are wrong (sha1sum).

**Comment by ethteck** [comment]
You're unable to reproduce it, you mean? Or you just don't know why it's happening
