### ISSUE TITLE
Identical numeric values considered different in diff

### ISSUE THREAD

**Issue by marijnvdwerf** [decompme/decomp.me#816]
<img width="664" alt="image" src="https://github.com/decompme/decomp.me/assets/737603/7ee25f4d-7ebb-4471-96db-9b2953721d4a">

https://decomp.me/scratch/xtJVv

The target has `0x1`, but the current version of the assembly displays `1`. I'd expect this difference to not be there in the first place, but _if_ it's different in both columns, I'd expect it to not count as an actual difference.

**Comment by ethteck** [comment]
I think this should be raised in asm-differ's repo

**Comment by ethteck** [comment]
the latter (assembled and then disassembled, but still)

**Comment by mkst** [comment]
With latest `maspsx` you can pass the `--expand-li` flag which solves this issue by expanding the pseudo instruction, e.g. see https://decomp.me/scratch/C38N9.

**Comment by mkst** [comment]
Am going to close this one as complete :+1:
