### ISSUE TITLE
Add support for agbcc -fprologue-bugfix

### ISSUE THREAD

**Issue by WhenGryphonsFly** [decompme/decomp.me#820]
Agbcc was recently updated to support a new compiler flag, `-fprologue-bugfix` (see https://github.com/pret/agbcc/pull/64). This option represents a compiler patch that removed unnecessary push/pop instructions in leaf functions. This flag is necessary to support some games such as Pokémon Pinball: Ruby and Sapphire.

I am not 100% sure this is the proper forum for this issue, but given that (a) the fork of agbcc being used by decomp.me (https://github.com/ethteck/agbcc) does not have issues enabled, and (b) the owner of that fork is a maintainer here, I thought that this was a good of a place as any. If there is a better location to file this bug / feature request please let me know.

**Comment by ethteck** [comment]
Hi, thanks for the issue. I think it might be a good time to switch the site to use pret's fork. However, I wrote my own ci / packaging stuff, so I'm not sure simply changing out the url would work. 

Someone will have to do a bit of work to make sure everything connects smoothly. If you're interested in giving it a shot, the first thing would be to set up the repo. Feel free to reach out in the discord if you have questions.

**Comment by ethteck** [comment]
Oh, I looked at this further and pret doesn't publish releases. Decomp.me needs a download link, so I think what needs to happen is either my fork needs pret's changes merged into it, or pret needs my release publishing merged into it.

**Comment by WhenGryphonsFly** [comment]
I had to update your workflow to replace some deprecated GitHub Actions, but I believe I have successfully merged your CI/packaging workflow into my fork of agbcc. With your permission, I can file a PR with these changes at pret's fork.

**Comment by ethteck** [comment]
Yeah, of course! glad my fork could help
