### ISSUE TITLE
Wanting to add support for Playstation 3, wondering how I can add the SDK

### ISSUE THREAD

**Issue by kernaltrap8** [decompme/decomp.me#848]
I was wondering how I would go about adding the Playstation 3's SDK/compiler to decomp.me. I have a local copy of just the compiler/SDK, but dont know how to go about adding it.

**Comment by ethteck** [comment]
I'd refer to [recent PRs](https://github.com/decompme/decomp.me/pull/802) that added platforms for this kind of thing. Also, what arch does ps3 use? Is it compatible with asm-differ? m2c? are there any active ps3 decomp projects? Are the compiler binaries windows, linux, etc? all of these are important considerations before trying to integrate it into the site

**Comment by JamesIsWack** [comment]
> I'd refer to [recent PRs](https://github.com/decompme/decomp.me/pull/802) that added platforms for this kind of thing. Also, what arch does ps3 use? Is it compatible with asm-differ? m2c? are there any active ps3 decomp projects? Are the compiler binaries windows, linux, etc? all of these are important considerations before trying to integrate it into the site

arch is PowerPC (big-endian), so asm-differ should support it. compiler binaries are win32 (windows), and i have a active decomp project which is why i want to integrate support: https://github.com/JamesIsWack/WoRmod

**Comment by ethteck** [comment]
If you're still interested in doing this, feel free to submit a PR. We have docs on how to add compilers and several example PRs for adding platforms you can follow as well. Closing this issue for now since I think the immediate question has been answered
