### ISSUE TITLE
Jump targets no longer properly decoded with PSYQ

### ISSUE THREAD

**Issue by nocato** [decompme/decomp.me#864]
It seems that the latest deployment of decomp.me introduced a regression in decoding jump targets with PSYQ.

An example of the problem: https://decomp.me/scratch/s6t07

Before the latest deployment, instruction at 0x438 properly decoded to:
```
j       580
```
and similarly for other jump instructions, so the scratch matched 100%.

After the latest deployment, the instruction now decodes to:
```
j       $.rel.text@00000580+0x180
```

The problem seems to occur only for jump instructions and not for conditional branches (like `beqz`).

**Comment by nocato** [comment]
The regression was introduced by this commit: "Overhaul download py (#855)" 4a2eabb34586d0a65a5830a5f9a4f6fdce79eafe (a commit before that works correctly).

This is what the raw output of `objdump` (adding print in decompme source) looked like before:
```
...
 80:	02002021 	move	a0,s0
 84:	08000024 	j	90 <NewSndtst_800C3594+0x90>
		84: R_MIPS_26	.text
 88:	00001021 	move	v0,zero
...
```

This is what it looks like after:
```
...
 80:	02002021 	move	a0,s0
 84:	08000024 	j	90 <NewSndtst_800C3594+0x90>
		84: R_MIPS_26	$.rel.text@00000090
 88:	00001021 	move	v0,zero
...
```

I don't know which upgraded tool (psyq-obj-parser? objdump? PSYQ itself?) causes the difference at 0x84.

**Comment by mkst** [comment]
Thanks for the report, there are a few variables at play here, but I believe it's a different very of the psyq obj parser. Let me investigate.

**Comment by mkst** [comment]
So, this is entirely on me. The site was using an old version of the psyq-obj-parser.

I've now build the latest version of the converter which has [this](https://github.com/grumpycoders/pcsx-redux/commit/a1a7cf76f3f84380bff34499ff7b3ca74546d73a) commit, so we are up to date. The new images have been published via [this](https://github.com/decompme/compilers/commit/e1beea065f147033d2afafa99f9424a005e77104) commit, so we just need to run `download.py` on the server to pull the latest psyq images and everything should be good.

I'll close this issue when that has been done. Feel free to test locally.

I've also had a look at trying to match this function using vanilla gcc2.8.1 + maspsx. Nearly there but something weird is happening with the sdata variables. Scratch is [here](https://decomp.me/scratch/qUAxB) if you're interested.

**Comment by mkst** [comment]
Right, two-for-1, fixed the relocs and improved maspsx, so both scratches are :ok:
