### ISSUE TITLE
"Try again" button on "We're having some trouble reaching the backend" page seems ineffective

### ISSUE THREAD

**Issue by ethteck** [decompme/decomp.me#870]
We now have a nicer page that pops up when the backend goes down, but unfortunately the "Try again" button seems to do nothing, even when the site is back up.

**Comment by nanaian** [comment]
We're calling [reset](https://nextjs.org/docs/app/api-reference/file-conventions/error#reset) - not sure why this doesn't work. A possible solution would be calling `window.location.reload()`

**Comment by ConorBobbleHat** [comment]
According to [this](https://github.com/vercel/next.js/discussions/49935), reset only forces a client-side re-render (and so retrying of requests), not a server one. If a server-side fetch failed, this results in the behavior we're seeing currently - a network error page ad infinitum. 

I can't seem to find an elegant way of forcing a server-side rerender, save Alex's solution of a full page reload.

I've patched that in in #1175
