### ISSUE TITLE
PresetId in new scratch page is not being saved in localStorage correctly.

### ISSUE THREAD

**Issue by DavidSM64** [decompme/decomp.me#907]
![Screenshot 2023-11-01 114850](https://github.com/decompme/decomp.me/assets/12130403/560ca212-56ea-454f-9c1c-81971e542d6d)

Whenever I load up the new scratch page, it says the presetId is "undefined". Which sets the preset to "Custom". Even though I always set it as "Diddy Kong Racing" (preset 27). Not a huge deal, but kinda annoying. This still occurs even if I clear the localStorage data.

I'm using Chrome 118.0.5993.118 on Windows 11.

**Comment by ethteck** [comment]
Thanks for the report. I'll look into this tomorrow

**Comment by DavidSM64** [comment]
Tested out on Firefox, and same issue occurs. Weird thing is that it does get saved into localStorage as `27`. But when I load the page it gets overwritten to be "undefined".

**Comment by nanaian** [comment]
This is because the presetId is a number & localStorage only allows strings. So when we get it out of localStorage upon page load, it is of the wrong type
