### ISSUE TITLE
Admin panel improvements

### ISSUE THREAD

**Issue by ethteck** [decompme/decomp.me#957]
- [ ] Json fields are so painful to edit
- [ ] Scratch claim tokens should just not be visible/editable from the admin panel, probably
- [ ] Loading a page of scratches in the admin panel takes 5 ages

![image](https://github.com/decompme/decomp.me/assets/2985314/6d088780-b1ee-4316-a19d-8a3534339bb7)

**Comment by bates64** [comment]
this seems like something we'd want to contribute to django?

**Comment by encounter** [comment]
I don’t see a reason to hide/read-only claim tokens, personally. Seems like it’d be useful for debugging eventually.

**Comment by mkst** [comment]
oh, are they not deleted once a scratch is claimed? I can add it back :)

**Comment by mkst** [comment]
![image](https://github.com/decompme/decomp.me/assets/22226349/763f0776-36a2-4d5e-a97b-5aea6ac30d74)

**Comment by encounter** [comment]
Yep! They’re nulled out once used

**Comment by ethteck** [comment]
he fixed it all
