### ISSUE TITLE
[PRESET] Create compiler preset "PaRappa the Rapper 2"

### ISSUE THREAD

**Issue by polybiusproxy** [decompme/decomp.me#963]
I would like to create a compiler preset on decomp.me.

- **Preset Name:** `PaRappa the Rapper 2`
- **Platform:** `ps2`
- **Compiler ID:** `ee-gcc2.9-991111-01`
- **Compiler Flags:** `-O2 -G8 -gstabs`

**Comment by mkst** [comment]
> The preset “[PaRappa the Rapper 2](https://decomp.me/admin/coreapp/preset/118/change/)” was added successfully.
